export const GET_DEPARTMENTS = 'GET_DEPARTMENTS'
export const DEPARTMENTS_LOADING = 'DEPARTMENTS_LOADING'
export const ADD_DEPARTMENT = 'ADD_DEPARTMENT'
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT'
export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT'








export const DELETE_DEPARTMENT_FAIL = 'DELETE_DEPARTMENT_FAIL'
export const ADD_DEPARTMENT_FAIL = 'ADD_DEPARTMENT_FAIL'
export const UPDATE_DEPARTMENT_FAIL = 'UPDATE_DEPARTMENT_FAIL'